package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Court generated by hbm2java
 */
public class Court extends Lookup {

	private static final long serialVersionUID = 5177702281866517622L;

	public Court() {
		super();

	}

}
