package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CourtSession generated by hbm2java
 */
public class CourtSession implements java.io.Serializable {

	private static final long serialVersionUID = -7636533085904819206L;
	private int id;
	private Lawsuit lawsuit;
	private Date date;
	private String decison;
	private String description;

	public CourtSession() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Lawsuit getLawsuit() {
		return this.lawsuit;
	}

	public void setLawsuit(Lawsuit lawsuit) {
		this.lawsuit = lawsuit;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDecison() {
		return this.decison;
	}

	public void setDecison(String decison) {
		this.decison = decison;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
