package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Education generated by hbm2java
 */
public class Education extends Lookup {

	private static final long serialVersionUID = 750844481520460300L;

	public Education() {
		super();

	}

}
