package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Governrate generated by hbm2java
 */
public class Governrate extends Lookup {

	private static final long serialVersionUID = -265784827217442472L;

	public Governrate() {
		super();

	}

}
