package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Hospital generated by hbm2java
 */
public class Hospital extends Lookup {

	private static final long serialVersionUID = -792824641619111487L;

	public Hospital() {
		super();

	}

}
