package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * ImageCategory generated by hbm2java
 */
public class ImageCategory extends Lookup {
	private static final long serialVersionUID = 7667268231006780993L;

	public ImageCategory() {
		super();

	}

}
