package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Injured generated by hbm2java
 */
public class Injured extends Victim {

	private static final long serialVersionUID = 3177464573951643989L;
	private final boolean martyr = false;

	/**
	 * @return the martyr
	 */
	public boolean isMartyr() {
		return martyr;
	}

}
