package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Job generated by hbm2java
 */
public class Job extends Lookup {

	private static final long serialVersionUID = -799561689791820066L;

	public Job() {
		super();

	}

}
