package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * LawOrganization generated by hbm2java
 */
public class LawOrganization extends Lookup {

	private static final long serialVersionUID = -1710287096351413112L;
	private Boolean isHumanRightCenter;
	private Set<Lawyer> lawyers = new HashSet<Lawyer>(0);

	public LawOrganization() {
		super();
	}

	public Boolean getIsHumanRightCenter() {
		return this.isHumanRightCenter;
	}

	public void setIsHumanRightCenter(Boolean isHumanRightCenter) {
		this.isHumanRightCenter = isHumanRightCenter;
	}

	public Set<Lawyer> getLawyers() {
		return this.lawyers;
	}

	public void setLawyers(Set<Lawyer> lawyers) {
		this.lawyers = lawyers;
	}

}
