package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Lawsuit generated by hbm2java
 */
public class Lawsuit implements java.io.Serializable {

	private static final long serialVersionUID = 6257701831763752570L;
	private int id;
	private Court court;
	private String description;
	private String judgeName;
	private String number;
	private Set<LawsuitLawyers> lawsuitLawyerses = new HashSet<LawsuitLawyers>(
			0);
	private Set<CourtSession> courtSessions = new HashSet<CourtSession>(0);
	private Set<Victim> victims = new HashSet<Victim>(0);

	public Lawsuit() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Court getCourt() {
		return this.court;
	}

	public void setCourt(Court court) {
		this.court = court;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getJudgeName() {
		return this.judgeName;
	}

	public void setJudgeName(String judgeName) {
		this.judgeName = judgeName;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Set<LawsuitLawyers> getLawsuitLawyerses() {
		return this.lawsuitLawyerses;
	}

	public void setLawsuitLawyerses(Set<LawsuitLawyers> lawsuitLawyerses) {
		this.lawsuitLawyerses = lawsuitLawyerses;
	}

	public Set<CourtSession> getCourtSessions() {
		return this.courtSessions;
	}

	public void setCourtSessions(Set<CourtSession> courtSessions) {
		this.courtSessions = courtSessions;
	}

	public Set<Victim> getVictims() {
		return this.victims;
	}

	public void setVictims(Set<Victim> victims) {
		this.victims = victims;
	}

}
