package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Martyr generated by hbm2java
 */
public class Martyr extends Victim {

	private static final long serialVersionUID = -7003495353677674847L;
	private final boolean martyr = true;
	private Area deathArea;
	private Date deathDate;

	private Area corpseDiscoveryArea;
	private Date corpseDiscoveryDate;

	public Martyr() {
	}

	/**
	 * @return the deathArea
	 */
	public Area getDeathArea() {
		return deathArea;
	}

	/**
	 * @param deathArea
	 *            the deathArea to set
	 */
	public void setDeathArea(Area deathArea) {
		this.deathArea = deathArea;
	}

	/**
	 * @return the deathDate
	 */
	public Date getDeathDate() {
		return deathDate;
	}

	/**
	 * @param deathDate
	 *            the deathDate to set
	 */
	public void setDeathDate(Date deathDate) {
		this.deathDate = deathDate;
	}

	/**
	 * @return the corpseDiscoveryArea
	 */
	public Area getCorpseDiscoveryArea() {
		return corpseDiscoveryArea;
	}

	/**
	 * @param corpseDiscoveryArea
	 *            the corpseDiscoveryArea to set
	 */
	public void setCorpseDiscoveryArea(Area corpseDiscoveryArea) {
		this.corpseDiscoveryArea = corpseDiscoveryArea;
	}

	/**
	 * @return the corpseDiscoveryDate
	 */
	public Date getCorpseDiscoveryDate() {
		return corpseDiscoveryDate;
	}

	/**
	 * @param corpseDiscoveryDate
	 *            the corpseDiscoveryDate to set
	 */
	public void setCorpseDiscoveryDate(Date corpseDiscoveryDate) {
		this.corpseDiscoveryDate = corpseDiscoveryDate;
	}

	/**
	 * @return the martyr
	 */
	public boolean isMartyr() {
		return martyr;
	}

}
