package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1


/**
 * Relationship generated by hbm2java
 */
public class Relationship extends Lookup {

	private static final long serialVersionUID = -3790580886191368588L;

	public Relationship() {
	}

}
