package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Area generated by hbm2java
 */
public class Source extends Lookup {

	private static final long serialVersionUID = 8344520386087853448L;

	public Source() {
		super();
	}

}
