package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import eg.net.lanNansahom.services.beans.ImageCategry;

/**
 * Victim generated by hbm2java
 */
public class Victim extends Person {

	private static final long serialVersionUID = -2401493263380362641L;
	private String description;
	private Date birthDate;
	private Integer age;
	private Area placeOfBirth;
	private String address;
	private Area residenceArea;

	private Education education;
	private Job job;
	private String employer;

	private Source source;

	private Area injuryArea;
	private Date injuryDate;
	private Hospital hospital;
	private String medicalDescription;

	// private Lawsuit lawsuit;

	private RecordStatus recordStatus;

	private List<Relative> relatives = new ArrayList<Relative>(0);
	private List<Image> images = new ArrayList<Image>(0);

	private List<Article> articles = new ArrayList<Article>(0);
	private List<Video> videos = new ArrayList<Video>(0);

	public Victim() {
	}

	/*
	 * public Lawsuit getLawsuit() { return this.lawsuit; }
	 * 
	 * public void setLawsuit(Lawsuit lawsuit) { this.lawsuit = lawsuit; }
	 */

	public Education getEducation() {
		return this.education;
	}

	public void setEducation(Education education) {
		this.education = education;
	}

	public Hospital getHospital() {
		return this.hospital;
	}

	public void setHospital(Hospital hospital) {
		this.hospital = hospital;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEmployer() {
		return this.employer;
	}

	public void setEmployer(String employer) {
		this.employer = employer;
	}

	/**
	 * @return the articles
	 */
	public List<Article> getArticles() {
		return articles;
	}

	/**
	 * @param articles
	 *            the articles to set
	 */
	public void setArticles(List<Article> articles) {
		this.articles = articles;
	}

	/**
	 * @return the relatives
	 */
	public List<Relative> getRelatives() {
		return relatives;
	}

	/**
	 * @param relatives
	 *            the relatives to set
	 */
	public void setRelatives(List<Relative> relatives) {
		this.relatives = relatives;
	}

	public List<Image> getImages() {
		return this.images;
	}

	public Image getImageByType(ImageCategry pCategory) {
		for (Image image : this.images) {
			if (image.getCategory().getId() == pCategory.getId()) {
				return image;
			}
		}
		return null;
	}

	public List<Image> getImagesByType(ImageCategry pCategory) {
		List<Image> result = new ArrayList<Image>();
		for (Image image : this.images) {
			if (image.getCategory().getId() == pCategory.getId()) {
				result.add(image);
			}
		}
		return result;
	}

	public void setImages(List<Image> images) {
		this.images = images;
	}

	public List<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(List<Video> videos) {
		this.videos = videos;
	}

	/**
	 * @return the age
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * @param age
	 *            the age to set
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * @return the placeOfBirth
	 */
	public Area getPlaceOfBirth() {
		return placeOfBirth;
	}

	/**
	 * @param placeOfBirth
	 *            the placeOfBirth to set
	 */
	public void setPlaceOfBirth(Area placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}

	/**
	 * @return the residenceArea
	 */
	public Area getResidenceArea() {
		return residenceArea;
	}

	/**
	 * @param residenceArea
	 *            the residenceArea to set
	 */
	public void setResidenceArea(Area residenceArea) {
		this.residenceArea = residenceArea;
	}

	/**
	 * @return the source
	 */
	public Source getSource() {
		return source;
	}

	/**
	 * @param source
	 *            the source to set
	 */
	public void setSource(Source source) {
		this.source = source;
	}

	/**
	 * @return the injuryArea
	 */
	public Area getInjuryArea() {
		return injuryArea;
	}

	/**
	 * @param injuryArea
	 *            the injuryArea to set
	 */
	public void setInjuryArea(Area injuryArea) {
		this.injuryArea = injuryArea;
	}

	/**
	 * @return the injuryDate
	 */
	public Date getInjuryDate() {
		return injuryDate;
	}

	/**
	 * @param injuryDate
	 *            the injuryDate to set
	 */
	public void setInjuryDate(Date injuryDate) {
		this.injuryDate = injuryDate;
	}

	public String getMedicalDescription() {
		return this.medicalDescription;
	}

	public void setMedicalDescription(String medicalDescription) {
		this.medicalDescription = medicalDescription;
	}

	/**
	 * @return the recordStatus
	 */
	public RecordStatus getRecordStatus() {
		return recordStatus;
	}

	/**
	 * @param recordStatus
	 *            the recordStatus to set
	 */
	public void setRecordStatus(RecordStatus recordStatus) {
		this.recordStatus = recordStatus;
	}

}
