package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * VideoCategory generated by hbm2java
 */
public class VideoCategory extends Lookup {

	private static final long serialVersionUID = 5087388181689667595L;

	public VideoCategory() {
		super();

	}

}
