package eg.net.lanNansahom.datamodel;

// Generated Aug 19, 2011 8:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Video generated by hbm2java
 */
public class Video implements java.io.Serializable {

	private static final long serialVersionUID = 4184103325346158746L;
	private int id;
	private String description;
	private String url;
	private String takenBy;
	private Date videoDate;
	private VideoCategory category;

	public Video() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTakenBy() {
		return this.takenBy;
	}

	public void setTakenBy(String takenBy) {
		this.takenBy = takenBy;
	}

	public Date getVideoDate() {
		return this.videoDate;
	}

	public void setVideoDate(Date videoDate) {
		this.videoDate = videoDate;
	}

	/**
	 * @return the category
	 */
	public VideoCategory getCategory() {
		return category;
	}

	/**
	 * @param category
	 *            the category to set
	 */
	public void setCategory(VideoCategory category) {
		this.category = category;
	}

}
